// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
// starting with 1 and 2, the first 10 terms will be:
// 
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
// the sum of the even-valued terms.

fn main() {

    let mut f = 1;
    let mut f1 = 1;
    let mut f2 = 0;
    let mut sum = 0;

    while f < 4000000 {

        f = f1 + f2;

        if f % 2 == 0 {
            sum += f;
        }

        f2 = f1;
        f1 = f;

    }

    println!("sum = {}", sum);
}
